// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type ActionCatalog struct {
	ID         int64     `json:"id"`
	ActionName string    `json:"action_name"`
	CreatedAt  time.Time `json:"created_at"`
}

type ActionRequired struct {
	ID              int64          `json:"id"`
	CallID          sql.NullInt64  `json:"call_id"`
	ActionCatalogID sql.NullInt64  `json:"action_catalog_id"`
	Notes           sql.NullString `json:"notes"`
}

type AlertService struct {
	ID                 int64         `json:"id"`
	ActionCatalogID    sql.NullInt64 `json:"action_catalog_id"`
	EmergencyServiceID sql.NullInt64 `json:"emergency_service_id"`
	AlwaysAlert        sql.NullBool  `json:"always_alert"`
}

type AlertedService struct {
	ID                 int64         `json:"id"`
	ActionRequiredID   sql.NullInt64 `json:"action_required_id"`
	EmergencyServiceID sql.NullInt64 `json:"emergency_service_id"`
}

type Call struct {
	ID            int64         `json:"id"`
	OperatorID    sql.NullInt64 `json:"operator_id"`
	PhoneNumberID sql.NullInt64 `json:"phone_number_id"`
	CityID        sql.NullInt64 `json:"city_id"`
	Notes         string        `json:"notes"`
	CreatedAt     time.Time     `json:"created_at"`
}

type City struct {
	ID        int64     `json:"id"`
	CityName  string    `json:"city_name"`
	CreatedAt time.Time `json:"created_at"`
}

type EmergencyService struct {
	ID            int64     `json:"id"`
	ServiceName   string    `json:"service_name"`
	ContactDetail string    `json:"contact_detail"`
	CreatedAt     time.Time `json:"created_at"`
}

type Operator struct {
	ID           int64          `json:"id"`
	OperatorCode sql.NullString `json:"operator_code"`
	Operator     string         `json:"operator"`
	CreatedAt    time.Time      `json:"created_at"`
}

type PhoneNumber struct {
	ID          int64          `json:"id"`
	PhoneNumber string         `json:"phone_number"`
	Notes       sql.NullString `json:"notes"`
	CreatedAt   time.Time      `json:"created_at"`
}

type Session struct {
	ID           uuid.UUID `json:"id"`
	Username     string    `json:"username"`
	RefreshToken string    `json:"refresh_token"`
	UserAgent    string    `json:"user_agent"`
	ClientIp     string    `json:"client_ip"`
	IsBlocked    bool      `json:"is_blocked"`
	ExpiresAt    time.Time `json:"expires_at"`
	CreatedAt    time.Time `json:"created_at"`
}

type User struct {
	Username          string    `json:"username"`
	HashedPassword    string    `json:"hashed_password"`
	FullName          string    `json:"full_name"`
	Email             string    `json:"email"`
	PasswordChangedAt time.Time `json:"password_changed_at"`
	CreatedAt         time.Time `json:"created_at"`
}
