// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateActionCatalog(ctx context.Context, actionName string) (ActionCatalog, error)
	CreateActionRequired(ctx context.Context, arg CreateActionRequiredParams) (ActionRequired, error)
	CreateAlertService(ctx context.Context, arg CreateAlertServiceParams) (AlertService, error)
	CreateAlertedService(ctx context.Context, arg CreateAlertedServiceParams) (AlertedService, error)
	CreateCall(ctx context.Context, arg CreateCallParams) (Call, error)
	CreateCity(ctx context.Context, cityName string) (City, error)
	CreateEmergencyService(ctx context.Context, arg CreateEmergencyServiceParams) (EmergencyService, error)
	CreateOperator(ctx context.Context, arg CreateOperatorParams) (Operator, error)
	CreatePhoneNumber(ctx context.Context, arg CreatePhoneNumberParams) (PhoneNumber, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteActionCatalog(ctx context.Context, id int64) error
	DeleteActionRequired(ctx context.Context, id int64) error
	DeleteAlertService(ctx context.Context, id int64) error
	DeleteAlertedService(ctx context.Context, id int64) error
	DeleteCall(ctx context.Context, id int64) error
	DeleteCity(ctx context.Context, id int64) error
	DeleteEmergencyService(ctx context.Context, id int64) error
	DeleteOperator(ctx context.Context, id int64) error
	DeletePhoneNumber(ctx context.Context, id int64) error
	GetCity(ctx context.Context, id int64) (City, error)
	GetSession(ctx context.Context, id uuid.UUID) (Session, error)
	GetUser(ctx context.Context, username string) (User, error)
	ListActionCatalog(ctx context.Context, arg ListActionCatalogParams) ([]ActionCatalog, error)
	ListActionRequired(ctx context.Context, arg ListActionRequiredParams) ([]ActionRequired, error)
	ListAlertService(ctx context.Context, arg ListAlertServiceParams) ([]AlertService, error)
	ListAlertedService(ctx context.Context, arg ListAlertedServiceParams) ([]AlertedService, error)
	ListCall(ctx context.Context, arg ListCallParams) ([]Call, error)
	ListCities(ctx context.Context, arg ListCitiesParams) ([]City, error)
	ListEmergencyService(ctx context.Context, arg ListEmergencyServiceParams) ([]EmergencyService, error)
	ListOperator(ctx context.Context, arg ListOperatorParams) ([]Operator, error)
	ListPhoneNumber(ctx context.Context, arg ListPhoneNumberParams) ([]PhoneNumber, error)
	UpdateActionCatalog(ctx context.Context, arg UpdateActionCatalogParams) (ActionCatalog, error)
	UpdateCity(ctx context.Context, arg UpdateCityParams) (City, error)
}

var _ Querier = (*Queries)(nil)
